name: Bug report - General
description: Create a report to help us improve.
title: "[Bug] General"
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Describe the bug

        A clear and concise description of what the bug is.

  - type: textarea
    id: reproduction_steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: error_log
    attributes:
      label: Error log (if it exists)
      description: If the log is too long, please upload it to mclo.gs and paste the link here.
      render: shell
      placeholder: https://mclo.gs/...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: input
    id: server_version
    attributes:
      label: Server brand and version
      placeholder: e.g. paper-1.21.11-132
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Anything else that may help reproduce or diagnose the issue.
    validations:
      required: false