name: Custom issue template
description: Describe the purpose of this issue template.
title: ""
labels: []

body:
  - type: textarea
    id: content
    attributes:
      label: Details
      placeholder: |
        Describe your issue here...
    validations:
      required: true